name: Build main packages
description: Build Spring Boot API, Config server, and front npm packages

runs:
  using: "composite"
  steps:
    - name: Build API package
      shell: ${{ runner.os == 'Windows' && 'cmd' || 'sh' }}
      run: mvn -DfinalName=vglservice clean package -f vglservice/pom.xml

    - name: Build Config server package
      shell: ${{ runner.os == 'Windows' && 'cmd' || 'sh' }}
      run: mvn -DfinalName=vglconfig clean package -f vglconfig/pom.xml

    - name: Build npm front package
      shell: ${{ runner.os == 'Windows' && 'cmd' || 'sh' }}
      run: npm install --prefix vglfront