version: '2'

services:
  vgldatabase:
    image: postgres:15.1-alpine
    restart: unless-stopped
    container_name: vgldatabase-nlb
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/vgl
    volumes:
      - vgldatabase-nlb:/data/vgl
    ports:
      - ${DB_PORT}:5432

  vglconfig:
    build: ./vglconfig
    image: vglconfig
    restart: unless-stopped
    container_name: vglconfig-nlb
    environment:
      - GIT_CONFIG_REPOSITORY=${GIT_CONFIG_REPOSITORY}
      - GIT_CONFIG_BRANCH=${GIT_CONFIG_BRANCH:-}
    volumes:
      - ./vglconfig/src/main/resources/application.properties:/usr/vglconfig/application.properties
      - ./vglconfig/server/docker/config:/usr/vglconfig/config # Necessary for Docker Desktop because host variables are not saved in containers: they are determined at runtime when the execution script is run
    ports:
      - ${CONFIG_SERVER_PORT}:8888

  vglservice:
    build: ./vglservice
    image: vglservice
    restart: unless-stopped
    container_name: vglservice-nlb
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - ENABLE_LOAD_BALANCING=false
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - API_ALLOWED_ORIGINS=${API_ALLOWED_ORIGINS}
    ports:
      - ${API_SERVER_PORT}:8080
    volumes:
      - ./vglservice/src/main/resources/application.properties:/usr/vglservice/application.properties
      - ./vglservice/server/docker/config:/usr/vglservice/config
    depends_on:
      - vglconfig
      - vgldatabase

  vglfront:
    build: ./vglfront
    image: vglfront
    restart: unless-stopped
    container_name: vglfront-nlb
    environment:
      - API_URL=${API_URL}
      - TEST_API_URL=${TEST_API_URL_NLB}
    volumes:
      - ./vglfront/src/assets:/usr/share/nginx/html/assets
      - ./vglfront/server/docker/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${FRONT_SERVER_PORT}:80

volumes:
  vgldatabase-nlb: