version: '2'

services:
  vgldatabase:
    image: postgres:15.1-alpine
    restart: unless-stopped
    container_name: vgldatabase
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/vgl
    volumes:
      - vgldatabase:/data/vgl
    ports:
      - ${DB_PORT}:5432

  vglconfig:
    build: ./vglconfig
    image: vglconfig
    restart: unless-stopped
    container_name: vglconfig
    environment:
      - GIT_CONFIG_REPOSITORY=${GIT_CONFIG_REPOSITORY}
      - GIT_CONFIG_BRANCH=${GIT_CONFIG_BRANCH:-master}
    volumes:
      - ./vglconfig/src/main/resources/application.properties:/usr/vglconfig/application.properties
    ports:
      - ${CONFIG_SERVER_PORT}:8888

  vglservice:
    build: ./vglservice
    image: vglservice
    restart: unless-stopped
    container_name: vglservice
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - EUREKA_SERVERS_URLS=${EUREKA_SERVERS_URLS}
      - API_ALLOWED_ORIGINS=${API_ALLOWED_ORIGINS}
      - API_HOSTNAME=${API_HOSTNAME:-}
    volumes:
      - ./vglservice/src/main/resources/application.properties:/usr/vglservice/application.properties
    ports:
      - ${API_SERVER_PORT}:8080
    depends_on:
      - vglconfig
      - vgldatabase
      - vglloadbalancer
      - vgldiscovery

  vglservice-two:
    build: ./vglservice
    image: vglservice
    restart: unless-stopped
    container_name: vglservice-two
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - EUREKA_SERVERS_URLS=${EUREKA_SERVERS_URLS}
      - API_ALLOWED_ORIGINS=${API_ALLOWED_ORIGINS}
      - API_HOSTNAME=${API_TWO_HOSTNAME:-}
    ports:
      - ${API_TWO_SERVER_PORT}:8080
    volumes:
      - ./vglservice/src/main/resources/application.properties:/usr/vglservice/application.properties
    depends_on:
      - vglconfig
      - vgldatabase
      - vglloadbalancer
      - vgldiscovery

  vglfront:
    build: ./vglfront
    image: vglfront
    restart: unless-stopped
    container_name: vglfront
    environment:
      - API_URL=${API_URL}
      - TEST_API_URL=${TEST_API_URL}
    volumes:
      - ./vglfront/src/assets:/usr/share/nginx/html/assets
      - ./vglfront/server/docker/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${FRONT_SERVER_PORT}:80

  vglloadbalancer:
    build: ./vglloadbalancer
    image: vglloadbalancer
    restart: unless-stopped
    container_name: vglloadbalancer
    environment:
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - EUREKA_SERVERS_URLS=${EUREKA_SERVERS_URLS}
      - LOADBALANCER_ALLOWED_ORIGINS=${LOADBALANCER_ALLOWED_ORIGINS}
      - LOADBALANCER_HOSTNAME=${LOADBALANCER_HOSTNAME:-}
    ports:
      - ${LOADBALANCER_SERVER_PORT}:10000
    volumes:
      - ./vglloadbalancer/src/main/resources/application.properties:/usr/vglloadbalancer/application.properties
    depends_on:
      - vglconfig
      - vgldiscovery

  vgldiscovery:
    build: ./vgldiscovery
    image: vgldiscovery
    restart: unless-stopped
    container_name: vgldiscovery
    environment:
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
    ports:
      - ${DISCOVERY_SERVER_PORT}:9999
    volumes:
      - ./vgldiscovery/src/main/resources/application.properties:/usr/vgldiscovery/application.properties
    depends_on:
      - vglconfig

volumes:
  vgldatabase: