version: "3"

services:
  vglconfig:
    build: ./vglconfig
    image: vglconfig:1.0.5-SNAPSHOT
    restart: on-failure
    container_name: vglconfig
    environment:
      - SERVER_PORT=${CONFIG_SERVER_PORT}
      - GIT_CONFIG_REPOSITORY=${GIT_CONFIG_REPOSITORY}
      - GIT_CONFIG_BRANCH=${GIT_CONFIG_BRANCH}
    ports:
      - ${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}

  vglservice:
    build: ./vglservice
    image: vglservice:2.5.7-SNAPSHOT
    restart: on-failure
    container_name: vglservice
    environment:
      - SERVER_PORT=${API_SERVER_PORT}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - ENABLE_LOAD_BALANCING=${ENABLE_LOAD_BALANCING}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
      - ALLOWED_ORIGINS=${API_ALLOWED_ORIGINS}
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    depends_on:
      - vglconfig

  vgldiscovery:
    build: ./vgldiscovery
    image: vgldiscovery:1.0.3-SNAPSHOT
    restart: on-failure
    container_name: vgldiscovery
    environment:
      - SERVER_PORT=${DISCOVERY_SERVER_PORT}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
    ports:
      - ${DISCOVERY_SERVER_PORT}:${DISCOVERY_SERVER_PORT}
    depends_on:
      - vglconfig

  vglloadbalancer:
    build: ./vglloadbalancer
    image: vglloadbalancer:1.0.4-SNAPSHOT
    restart: on-failure
    container_name: vglloadbalancer
    environment:
      - SERVER_PORT=${LOADBALANCER_SERVER_PORT}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
      - ALLOWED_ORIGINS=${LOADBALANCER_ALLOWED_ORIGINS}
    ports:
      - ${LOADBALANCER_SERVER_PORT}:${LOADBALANCER_SERVER_PORT}
    depends_on:
      - vglconfig
      - vgldiscovery

  vglfront:
    build: ./vglfront
    image: vglfront:0.4.7-SNAPSHOT
    restart: on-failure
    container_name: vglfront
    environment:
      - SERVER_PORT=${FRONT_SERVER_PORT}
      - API_URL=${API_URL}
      - TEST_API_URL=${TEST_API_URL}
    volumes:
      - ./vglfront/src/assets:/usr/share/nginx/html/assets
      - ./vglfront/server/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${FRONT_SERVER_PORT}:80
    depends_on:
      - vglconfig
      - vglservice
      - vgldiscovery
      - vglloadbalancer