version: "3"

services:
  vglconfig:
    build: ./vglconfig
    image: vglconfig:1.0.5-SNAPSHOT
    restart: on-failure
    container_name: vglconfig-nlb
    environment:
      - SERVER_PORT=${CONFIG_SERVER_PORT}
      - GIT_CONFIG_REPOSITORY=${GIT_CONFIG_REPOSITORY}
      - GIT_CONFIG_BRANCH=${GIT_CONFIG_BRANCH:-master}
    ports:
      - ${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}

  vglservice:
    build: ./vglservice
    image: vglservice:2.5.8-SNAPSHOT
    restart: on-failure
    container_name: vglservice-nlb
    environment:
      - SERVER_PORT=${API_SERVER_PORT}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - ALLOWED_ORIGINS=${API_ALLOWED_ORIGINS}
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    depends_on:
      - vglconfig

  vglfront:
    build: ./vglfront
    image: vglfront:0.4.8-SNAPSHOT
    restart: on-failure
    container_name: vglfront-nlb
    environment:
      - SERVER_PORT=${FRONT_SERVER_PORT}
      - API_URL=${API_URL}
      - TEST_API_URL=${TEST_API_URL_NLB}
    volumes:
      - ./vglfront/src/assets:/usr/share/nginx/html/assets
      - ./vglfront/server/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${FRONT_SERVER_PORT}:80
    depends_on:
      - vglconfig
      - vglservice