version: '2'

services:
  lddatabase:
    image: postgres:15.1-alpine
    restart: unless-stopped
    container_name: lddatabase-nlb
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/lds
    volumes:
      - lddatabase-nlb:/data/lds
    ports:
      - ${DB_PORT}:5432

  ldconfig:
    build: ./ldconfig
    image: ldconfig
    restart: unless-stopped
    container_name: ldconfig-nlb
    environment:
      - GIT_CONFIG_REPOSITORY=${GIT_CONFIG_REPOSITORY}
      - GIT_CONFIG_BRANCH=${GIT_CONFIG_BRANCH:-}
    volumes:
      - ./ldconfig/src/main/resources/application.properties:/usr/ldconfig/application.properties
      - ./ldconfig/server/docker/config:/usr/ldconfig/config # Necessary for Docker Desktop because host variables are not saved in containers: they are determined at runtime when the execution script is run
    ports:
      - ${CONFIG_SERVER_PORT}:8888

  ldservice:
    build: ./ldservice
    image: ldservice
    restart: unless-stopped
    container_name: ldservice-nlb
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - ENABLE_LOAD_BALANCING=false
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - API_ALLOWED_ORIGINS=${API_ALLOWED_ORIGINS}
    ports:
      - ${API_SERVER_PORT}:8080
    volumes:
      - ./ldservice/src/main/resources/application.properties:/usr/ldservice/application.properties
      - ./ldservice/server/docker/config:/usr/ldservice/config
    depends_on:
      - ldconfig
      - lddatabase

  ldfront:
    build: ./ldfront
    image: ldfront
    restart: unless-stopped
    container_name: ldfront-nlb
    environment:
      - API_URL=${API_URL}
      - TEST_API_URL=${TEST_API_URL_NLB}
    volumes:
      - ./ldfront/src/assets:/usr/share/nginx/html/assets
      - ./ldfront/server/docker/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${FRONT_SERVER_PORT}:80

volumes:
  lddatabase-nlb: