version: "3"

services:
  vglfront:
    build: .
    image: vglfront:0.4.7-SNAPSHOT
    restart: on-failure
    container_name: vglfront
    environment:
      - SERVER_PORT=${FRONT_SERVER_PORT}
      - API_URL=${API_URL}
      - TEST_API_URL=${TEST_API_URL}
    volumes:
      - ./src/assets:/usr/share/nginx/html/assets
      - ./server/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${FRONT_SERVER_PORT}:80
    networks:
      - vglfront
networks:
  vglfront:
    external:
      name: vglnetwork