name: Build & test with Load Balancing
on: push

jobs:
  build-test-lb:
    name: ${{ matrix.os }} - Build & test with Load Balancing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up CI/CD builders
        uses: ./.github/actions/setup

      - name: Build main components (API, Config server)
        uses: ./.github/actions/build-main

      - name: Build Load Balancing related components (Eureka discovery server, Load Balancing server)
        uses: ./.github/actions/build-lb

      - name: Change default front server port
        shell: bash
        run: echo $'\nFRONT_SERVER_PORT=4201' >> vglfront/.env

      # Run with Linux / Darwin based environment
      - name: Run Config server (Linux / Darwin environment)
        if: runner.os != 'Windows'
        run: java -DGIT_CONFIG_BRANCH=${{github.head_ref || github.ref_name}} -DGIT_CONFIG_REPOSITORY=https://github.com/Zemasterkrom/spring-cloud-video-games-api-config -XX:TieredStopAtLevel=1 -jar vglconfig/target/vglconfig.jar &

      - name: Run Spring Boot API (Linux / Darwin environment)
        if: runner.os != 'Windows'
        run: java -DALLOWED_ORIGINS=http://localhost:4201 -XX:TieredStopAtLevel=1 -jar vglservice/target/vglservice.jar &

      - name: Run Eureka discovery server (Linux / Darwin environment)
        if: runner.os != 'Windows'
        run: java -XX:TieredStopAtLevel=1 -jar vgldiscovery/target/vgldiscovery.jar &

      - name: Run Load Balancing server (Linux / Darwin environment)
        if: runner.os != 'Windows'
        run: java -XX:TieredStopAtLevel=1 -jar vglloadbalancer/target/vglloadbalancer.jar &

      - name: Run npm front (Linux / Darwin environment)
        if: runner.os != 'Windows'
        run: |
          cd vglfront
          npm run start &

      # Run with Windows based environment
      - name: Run Config server (Windows environment)
        if: runner.os == 'Windows'
        shell: cmd
        run: start java -DGIT_CONFIG_BRANCH=${{github.head_ref || github.ref_name}} -DGIT_CONFIG_REPOSITORY=https://github.com/Zemasterkrom/spring-cloud-video-games-api-config -XX:TieredStopAtLevel=1 -jar vglconfig/target/vglconfig.jar

      - name: Run Spring Boot API (Windows environment)
        if: runner.os == 'Windows'
        shell: cmd
        run: start java -DALLOWED_ORIGINS=http://localhost:4201 -XX:TieredStopAtLevel=1 -jar vglservice/target/vglservice.jar

      - name: Run Eureka discovery server (Windows environment)
        if: runner.os == 'Windows'
        shell: cmd
        run: start java -XX:TieredStopAtLevel=1 -jar vgldiscovery/target/vgldiscovery.jar

      - name: Run Load Balancing server (Windows environment)
        if: runner.os == 'Windows'
        shell: cmd
        run: start java -XX:TieredStopAtLevel=1 -jar vglloadbalancer/target/vglloadbalancer.jar

      - name: Run npm front (Windows environment)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          cd vglfront
          start npm run start

      - name: Test API and front
        uses: ./.github/actions/test-lb

  build-test-lb-docker:
    name: ${{ matrix.os }} - Build & test with Load Balancing (Docker)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v3
      - uses: docker-practice/actions-setup-docker@master
        if: runner.os == 'macOS'

      - name: Change default front server port
        shell: bash
        run: |
          echo $'\nFRONT_SERVER_PORT=4201' >> .env
          echo $'\nAPI_ALLOWED_ORIGINS=http://localhost:4201' >> .env
          echo $'\nLOADBALANCER_ALLOWED_ORIGINS=http://localhost:4201' >> .env

      - name: Launch containers
        run: GIT_CONFIG_BRANCH=${{github.head_ref || github.ref_name}} docker compose up -d --build

      - name: Test API and front
        uses: ./.github/actions/test-lb