name: Build and test with Load Balancing
on: push

jobs:

  build-test-lb-docker:
    name: ${{ matrix.os }} - Build and test with Load Balancing (Docker)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Change default front server port
        shell: bash
        run: |
          echo $'\nFRONT_SERVER_PORT=4201' >> .env
          echo $'\nAPI_ALLOWED_ORIGINS=http://localhost:4201' >> .env
          echo $'\nLOADBALANCER_ALLOWED_ORIGINS=http://localhost:4201' >> .env

      - name: Clean up memory
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Install Docker on macOS
        if: runner.os == 'macOS'
        run: |
          brew install docker docker-compose
          mkdir -p ~/.docker/cli-plugins
          ln -sfn $(brew --prefix)/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
          colima start

      - name: Launch containers
        run: |
          GIT_CONFIG_BRANCH=${{github.head_ref || github.ref_name}} docker compose build vglconfig vglservice
          GIT_CONFIG_BRANCH=${{github.head_ref || github.ref_name}} docker compose build vgldiscovery vglloadbalancer 
          GIT_CONFIG_BRANCH=${{github.head_ref || github.ref_name}} docker compose up --build

      - name: Test API and front
        uses: ./.github/actions/test-lb