name: Build and test without Load Balancing
on: push

jobs:
  build-test-nlb-docker:
    name: ${{ matrix.os }} - Build and test without Load Balancing (Docker)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Change default front server port
        shell: bash
        run: |
          echo $'\nFRONT_SERVER_PORT=4201' >> no-load-balancing.env
          echo $'\nAPI_ALLOWED_ORIGINS=http://localhost:4201' >> no-load-balancing.env

      - name: Install Docker on macOS
        if: runner.os == 'macOS'
        run: |
          brew install docker docker-compose
          mkdir -p ~/.docker/cli-plugins
          ln -sfn $(brew --prefix)/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
          colima start

      - name: Launch containers
        run: GIT_CONFIG_BRANCH=${{github.head_ref || github.ref_name}} docker compose --env-file no-load-balancing.env -f docker-compose-no-load-balancing.yml up -d --build

      - name: Test API and front
        uses: ./.github/actions/test-main